apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backend-svc
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: 'TCP'
  selector:
    app: {{ .Values.name }}-backend
    tier: backend
  type: ClusterIP