apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-frontend-svc
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30146
      protocol: 'TCP'
  selector:
    app: {{ .Values.name }}-frontend
    tier: frontend
  type: NodePort