apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-frontend
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}-frontend
      tier: frontend
  replicas: {{ .Values.frontend_replica }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-frontend
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.deployment_frontend.image }}:{{ .Values.deployment_frontend.tag }}
        name: {{ .Values.name }}-frontend
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2
        resources:
          requests:
            cpu: "250m"
            memory: "256M"
          limits:
            cpu: "1000m"
            memory: "1000M"        