apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: {{ .Values.name }}
    tier: mongodb
  type: ClusterIP