apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tier: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-secret
              key: password
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: "100m"
            memory: "256M"
          limits:
            cpu: "1500m"
            memory: "1000M"
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
